services:
  dev_postgres:
    image: postgres:17
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: master123
      POSTGRES_DB: postgres
    volumes:
      - ./dbdata/postgresql/data:/var/lib/postgresql/data
    networks:
      - full-stack-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  full-stack-network:
    external: true